from enum import Enum


class LinkStatus(str, Enum):
    ADEQUATE = "ADEQUATE"
    PARTIAL = "PARTIAL"
    INADEQUATE = "INADEQUATE"
    MISSING = "MISSING"
    CONFLICT = "CONFLICT"
    ORPHAN_TEST = "ORPHAN_TEST"


class RuleFlag(str, Enum):
    NUMERIC_MISMATCH = "NUMERIC_MISMATCH"
    NUMERIC_PARTIAL_MISMATCH = "NUMERIC_PARTIAL_MISMATCH"
    RANGE_DIRECTION_CONFLICT = "RANGE_DIRECTION_CONFLICT"
    TIMEOUT_MISMATCH = "TIMEOUT_MISMATCH"
    ATTEMPT_MISMATCH = "ATTEMPT_MISMATCH"
    SIZE_LIMIT_MISMATCH = "SIZE_LIMIT_MISMATCH"
    ROLE_MISMATCH = "ROLE_MISMATCH"
    CONDITION_MISMATCH = "CONDITION_MISMATCH"
    EXPECTED_RESULT_MISSING = "EXPECTED_RESULT_MISSING"
    PARTIAL_KEYWORD_MATCH = "PARTIAL_KEYWORD_MATCH"
    LOW_RELEVANCE = "LOW_RELEVANCE"


class FindingType(str, Enum):
    REQUIREMENT = "REQUIREMENT"
    ORPHAN_TEST = "ORPHAN_TEST"
